export interface City {
  Id: number;
  Name: string;
}
export class Cities {
  public static Data: City[] = [
    { Id: 1, Name: "Karachi" },
    { Id: 2, Name: "Lahore" },
    { Id: 3, Name: "Islamabad" },
    { Id: 4, Name: "Rawalpindi" },
    { Id: 5, Name: "Peshawar" },
    { Id: 6, Name: "Abbottabad" },
    { Id: 7, Name: "Abdul Hakeem" },
    { Id: 8, Name: "Adda jahan khan" },
    { Id: 9, Name: "Adda shaiwala" },
    { Id: 10, Name: "Ahmed Pur East" },
    { Id: 11, Name: "Ahmedpur Lamma" },
    { Id: 12, Name: "Akora khattak" },
    { Id: 13, Name: "Ali chak" },
    { Id: 14, Name: "Alipur Chatta" },
    { Id: 15, Name: "Allahabad" },
    { Id: 16, Name: "Amangarh" },
    { Id: 17, Name: "Arifwala" },
    { Id: 18, Name: "Attock" },
    { Id: 19, Name: "Babarloi" },
    { Id: 20, Name: "Babri banda" },
    { Id: 21, Name: "Badin" },
    { Id: 22, Name: "Bahawalnagar" },
    { Id: 23, Name: "Bahawalpur" },
    { Id: 24, Name: "Balakot" },
    { Id: 25, Name: "Bannu" },
    { Id: 26, Name: "Baroute" },
    { Id: 27, Name: "Basirpur" },
    { Id: 28, Name: "Basti Shorekot" },
    { Id: 29, Name: "Bat khela" },
    { Id: 30, Name: "Batang" },
    { Id: 31, Name: "Bhai pheru" },
    { Id: 32, Name: "Bhakkar" },
    { Id: 33, Name: "Bhalwal" },
    { Id: 34, Name: "Bhan saeedabad" },
    { Id: 35, Name: "Bhera" },
    { Id: 36, Name: "Bhikky" },
    { Id: 37, Name: "Bhimber" },
    { Id: 38, Name: "Bhirya road" },
    { Id: 39, Name: "Bhuawana" },
    { Id: 40, Name: "Buchay key" },
    { Id: 41, Name: "Buner" },
    { Id: 42, Name: "Burewala" },
    { Id: 43, Name: "Chaininda" },
    { Id: 44, Name: "Chak 4 b c" },
    { Id: 45, Name: "Chak 46" },
    { Id: 46, Name: "Chak jamal" },
    { Id: 47, Name: "Chak jhumra" },
    { Id: 48, Name: "Chak Shahzad" },
    { Id: 49, Name: "Chaklala" },
    { Id: 50, Name: "Chaksawari" },
    { Id: 51, Name: "Chakwal" },
    { Id: 52, Name: "Charsadda" },
    { Id: 53, Name: "Chashma" },
    { Id: 54, Name: "Chawinda" },
    { Id: 55, Name: "Chenab Nagar" },
    { Id: 56, Name: "Chichawatni" },
    { Id: 57, Name: "Chiniot" },
    { Id: 58, Name: "Chishtian" },
    { Id: 59, Name: "Chitral" },
    { Id: 60, Name: "Chohar jamali" },
    { Id: 61, Name: "Choppar hatta" },
    { Id: 62, Name: "Chowha saidan shah" },
    { Id: 63, Name: "Chowk azam" },
    { Id: 64, Name: "Chowk mailta" },
    { Id: 65, Name: "Chowk munda" },
    { Id: 66, Name: "Chunian" },
    { Id: 67, Name: "D.G.Khan" },
    { Id: 68, Name: "Dadakhel" },
    { Id: 69, Name: "Dadu" },
    { Id: 70, Name: "Dadyal Ak" },
    { Id: 71, Name: "Daharki" },
    { Id: 72, Name: "Dandot" },
    { Id: 73, Name: "Dargai" },
    { Id: 74, Name: "Darya khan" },
    { Id: 75, Name: "Daska" },
    { Id: 76, Name: "Daud khel" },
    { Id: 77, Name: "Daulatpur" },
    { Id: 78, Name: "Deh pathan" },
    { Id: 79, Name: "Depal pur" },
    { Id: 80, Name: "Dera Allah Yar" },
    { Id: 81, Name: "Dera ismail khan" },
    { Id: 82, Name: "Dera murad jamali" },
    { Id: 83, Name: "Dera nawab sahib" },
    { Id: 84, Name: "Dhatmal" },
    { Id: 85, Name: "Dhoun kal" },
    { Id: 86, Name: "Digri" },
    { Id: 87, Name: "Dijkot" },
    { Id: 88, Name: "Dina" },
    { Id: 89, Name: "Dinga" },
    { Id: 90, Name: "Dir" },
    { Id: 91, Name: "Doaba" },
    { Id: 92, Name: "Doltala" },
    { Id: 93, Name: "Domeli" },
    { Id: 94, Name: "Donga Bonga" },
    { Id: 95, Name: "Dudial" },
    { Id: 96, Name: "Dunia Pur" },
    { Id: 97, Name: "Eminabad" },
    { Id: 98, Name: "Esa Khel" },
    { Id: 99, Name: "Faisalabad" },
    { Id: 100, Name: "Faqirwali" },
    { Id: 101, Name: "Farooqabad" },
    { Id: 102, Name: "Fateh Jang" },
    { Id: 103, Name: "Fateh pur" },
    { Id: 104, Name: "Feroz walla" },
    { Id: 105, Name: "Feroz watan" },
    { Id: 106, Name: "Feroz Watwan" },
    { Id: 107, Name: "Fiza got" },
    { Id: 108, Name: "Fort Abbass" },
    { Id: 109, Name: "Gadoon amazai" },
    { Id: 110, Name: "Gaggo mandi" },
    { Id: 111, Name: "Gakhar mandi" },
    { Id: 112, Name: "Gambat" },
    { Id: 113, Name: "Gambet" },
    { Id: 114, Name: "Garh maharaja" },
    { Id: 115, Name: "Garh more" },
    { Id: 116, Name: "Garhi yaseen" },
    { Id: 117, Name: "Gari habibullah" },
    { Id: 118, Name: "Gari mori" },
    { Id: 119, Name: "Gharo" },
    { Id: 120, Name: "Ghazi" },
    { Id: 121, Name: "Ghotki" },
    { Id: 122, Name: "Gilgit" },
    { Id: 123, Name: "Gohar ghoushti" },
    { Id: 124, Name: "Gojra" },
    { Id: 125, Name: "Goth Machi" },
    { Id: 126, Name: "Goular khel" },
    { Id: 127, Name: "Guddu" },
    { Id: 128, Name: "Gujar khan" },
    { Id: 129, Name: "Gujar Khan" },
    { Id: 130, Name: "Gujranwala" },
    { Id: 131, Name: "Gujrat" },
    { Id: 132, Name: "Gwadar" },
    { Id: 133, Name: "Hafizabad" },
    { Id: 134, Name: "Hala" },
    { Id: 135, Name: "Hangu" },
    { Id: 136, Name: "Harappa" },
    { Id: 137, Name: "Haripur" },
    { Id: 138, Name: "Hariwala" },
    { Id: 139, Name: "Haroonabad" },
    { Id: 140, Name: "Hasilpur" },
    { Id: 141, Name: "Hassan abdal" },
    { Id: 142, Name: "Hattar" },
    { Id: 143, Name: "Hattian" },
    { Id: 144, Name: "Hattian lawrencepur" },
    { Id: 145, Name: "Havali Lakhan" },
    { Id: 146, Name: "Hawilian" },
    { Id: 147, Name: "Hayatabad" },
    { Id: 148, Name: "Hazro" },
    { Id: 149, Name: "Head marala" },
    { Id: 150, Name: "Hub" },
    { Id: 151, Name: "Hub-Balochistan" },
    { Id: 152, Name: "Hujra Shah Mukeem" },
    { Id: 153, Name: "Hunza" },
    { Id: 154, Name: "Hyderabad" },
    { Id: 155, Name: "Iskandarabad" },
    { Id: 156, Name: "Jacobabad" },
    { Id: 157, Name: "Jahaniya" },
    { Id: 158, Name: "Jaja abasian" },
    { Id: 159, Name: "Jalalpur Jattan" },
    { Id: 160, Name: "Jalalpur Pirwala" },
    { Id: 161, Name: "Jampur" },
    { Id: 162, Name: "Jamrud road" },
    { Id: 163, Name: "Jamshoro" },
    { Id: 164, Name: "Jan pur" },
    { Id: 165, Name: "Jand" },
    { Id: 166, Name: "Jandanwala" },
    { Id: 167, Name: "Jaranwala" },
    { Id: 168, Name: "Jatlaan" },
    { Id: 169, Name: "Jatoi" },
    { Id: 170, Name: "Jauharabad" },
    { Id: 171, Name: "Jehangira" },
    { Id: 172, Name: "Jhal Magsi" },
    { Id: 173, Name: "Jhand" },
    { Id: 174, Name: "Jhang" },
    { Id: 175, Name: "Jhatta bhutta" },
    { Id: 176, Name: "Jhelum" },
    { Id: 177, Name: "Jhudo" },
    { Id: 178, Name: "Jin Pur" },
    { Id: 179, Name: "K.N. Shah" },
    { Id: 180, Name: "Kabirwala" },
    { Id: 181, Name: "Kacha khooh" },
    { Id: 182, Name: "Kahuta" },
    { Id: 183, Name: "Kakul" },
    { Id: 184, Name: "Kakur town" },
    { Id: 185, Name: "Kala bagh" },
    { Id: 186, Name: "Kala shah kaku" },
    { Id: 187, Name: "Kalaswala" },
    { Id: 188, Name: "Kallar Kahar" },
    { Id: 189, Name: "Kallar Saddiyian" },
    { Id: 190, Name: "Kallur kot" },
    { Id: 191, Name: "Kamalia" },
    { Id: 192, Name: "Kamalia musa" },
    { Id: 193, Name: "Kamber ali khan" },
    { Id: 194, Name: "Kameer" },
    { Id: 195, Name: "Kamoke" },
    { Id: 196, Name: "Kamra" },
    { Id: 197, Name: "Kandh kot" },
    { Id: 198, Name: "Kandiaro" },
    { Id: 199, Name: "Karak" },
    { Id: 200, Name: "Karoor pacca" },
    { Id: 201, Name: "Karore lalisan" },
    { Id: 202, Name: "Kashmir" },
    { Id: 203, Name: "Kashmore" },
    { Id: 204, Name: "Kasur" },
    { Id: 205, Name: "Kazi ahmed" },
    { Id: 206, Name: "Khairpur" },
    { Id: 207, Name: "Khairpur Mir" },
    { Id: 208, Name: "Khan Bela" },
    { Id: 209, Name: "Khan qah sharif" },
    { Id: 210, Name: "Khandabad" },
    { Id: 211, Name: "Khanewal" },
    { Id: 212, Name: "Khangarh" },
    { Id: 213, Name: "Khanpur" },
    { Id: 214, Name: "Khanqah dogran" },
    { Id: 215, Name: "Khanqah sharif" },
    { Id: 216, Name: "Kharian" },
    { Id: 217, Name: "Khewra" },
    { Id: 218, Name: "Khoski" },
    { Id: 219, Name: "Khudian Khas" },
    { Id: 220, Name: "Khurian wala" },
    { Id: 221, Name: "Khurrianwala" },
    { Id: 222, Name: "Khushab" },
    { Id: 223, Name: "Khushal kot" },
    { Id: 224, Name: "Khuzdar" },
    { Id: 225, Name: "Khyber" },
    { Id: 226, Name: "Klaske" },
    { Id: 227, Name: "Kohat" },
    { Id: 228, Name: "Kot addu" },
    { Id: 229, Name: "Kot bunglow" },
    { Id: 230, Name: "Kot ghulam mohd" },
    { Id: 231, Name: "Kot mithan" },
    { Id: 232, Name: "Kot Momin" },
    { Id: 233, Name: "Kot radha kishan" },
    { Id: 234, Name: "Kotla" },
    { Id: 235, Name: "Kotla arab ali khan" },
    { Id: 236, Name: "Kotla jam" },
    { Id: 237, Name: "Kotla Pathan" },
    { Id: 238, Name: "Kotli Ak" },
    { Id: 239, Name: "Kotli Loharan" },
    { Id: 240, Name: "Kotri" },
    { Id: 241, Name: "Kumbh" },
    { Id: 242, Name: "Kundina" },
    { Id: 243, Name: "Kunjah" },
    { Id: 244, Name: "Kunri" },
    { Id: 245, Name: "Lakki marwat" },
    { Id: 246, Name: "Lala musa" },
    { Id: 247, Name: "Lala rukh" },
    { Id: 248, Name: "Laliah" },
    { Id: 249, Name: "Lalshanra" },
    { Id: 250, Name: "Larkana" },
    { Id: 251, Name: "Lasbela" },
    { Id: 252, Name: "Lawrence pur" },
    { Id: 253, Name: "Layyah" },
    { Id: 254, Name: "Liaqat Pur" },
    { Id: 255, Name: "Lodhran" },
    { Id: 256, Name: "Lower Dir" },
    { Id: 257, Name: "Ludhan" },
    { Id: 258, Name: "Madina" },
    { Id: 259, Name: "Makli" },
    { Id: 260, Name: "Malakand Agency" },
    { Id: 261, Name: "Malakwal" },
    { Id: 262, Name: "Mamu kunjan" },
    { Id: 263, Name: "Mandi bahauddin" },
    { Id: 264, Name: "Mandra" },
    { Id: 265, Name: "Manga mandi" },
    { Id: 266, Name: "Mangal sada" },
    { Id: 267, Name: "Mangi" },
    { Id: 268, Name: "Mangla" },
    { Id: 269, Name: "Mangowal" },
    { Id: 270, Name: "Manoabad" },
    { Id: 271, Name: "Mansehra" },
    { Id: 272, Name: "Mardan" },
    { Id: 273, Name: "Mari indus" },
    { Id: 274, Name: "Mastoi" },
    { Id: 275, Name: "Matli" },
    { Id: 276, Name: "Mehar" },
    { Id: 277, Name: "Mehmood kot" },
    { Id: 278, Name: "Mehrabpur" },
    { Id: 279, Name: "Melsi" },
    { Id: 280, Name: "Mian Channu" },
    { Id: 281, Name: "Mian Wali" },
    { Id: 282, Name: "Minchanabad" },
    { Id: 283, Name: "Mingora" },
    { Id: 284, Name: "Mir ali" },
    { Id: 285, Name: "Miran shah" },
    { Id: 286, Name: "Mirpur A.K." },
    { Id: 287, Name: "Mirpur khas" },
    { Id: 288, Name: "Mirpur mathelo" },
    { Id: 289, Name: "Mithi" },
    { Id: 290, Name: "Mitiari" },
    { Id: 291, Name: "Mohen jo daro" },
    { Id: 292, Name: "More kunda" },
    { Id: 293, Name: "Morgah" },
    { Id: 294, Name: "Moro" },
    { Id: 295, Name: "Mubarik pur" },
    { Id: 296, Name: "Multan" },
    { Id: 297, Name: "Muridke" },
    { Id: 298, Name: "Murree" },
    { Id: 299, Name: "Musafir khana" },
    { Id: 300, Name: "Mustung" },
    { Id: 301, Name: "Muzaffar Gargh" },
    { Id: 302, Name: "Muzaffarabad" },
    { Id: 303, Name: "Nankana sahib" },
    { Id: 304, Name: "Narang mandi" },
    { Id: 305, Name: "Narowal" },
    { Id: 306, Name: "Naseerabad" },
    { Id: 307, Name: "Naukot" },
    { Id: 308, Name: "Naukundi" },
    { Id: 309, Name: "Nawabshah" },
    { Id: 310, Name: "New saeedabad" },
    { Id: 311, Name: "Nilore" },
    { Id: 312, Name: "Noor kot" },
    { Id: 313, Name: "Nooriabad" },
    { Id: 314, Name: "Noorpur nooranga" },
    { Id: 315, Name: "Noshero Feroze" },
    { Id: 316, Name: "Noudero" },
    { Id: 317, Name: "Nowshera" },
    { Id: 318, Name: "Nowshera cantt" },
    { Id: 319, Name: "Nowshera Virka" },
    { Id: 320, Name: "Okara" },
    { Id: 321, Name: "Other" },
    { Id: 322, Name: "Padidan" },
    { Id: 323, Name: "Pak china fertilizer" },
    { Id: 324, Name: "Pak pattan sharif" },
    { Id: 325, Name: "Panjan kisan" },
    { Id: 326, Name: "Panjgoor" },
    { Id: 327, Name: "Pano Aqil" },
    { Id: 328, Name: "Pano Aqil" },
    { Id: 329, Name: "Pasni" },
    { Id: 330, Name: "Pasrur" },
    { Id: 331, Name: "Pattoki" },
    { Id: 332, Name: "Phagwar" },
    { Id: 333, Name: "Phalia" },
    { Id: 334, Name: "Phool nagar" },
    { Id: 335, Name: "Piaro goth" },
    { Id: 336, Name: "Pind Dadan Khan" },
    { Id: 337, Name: "Pindi Bhattian" },
    { Id: 338, Name: "Pindi bohri" },
    { Id: 339, Name: "Pindi gheb" },
    { Id: 340, Name: "Piplan" },
    { Id: 341, Name: "Pir mahal" },
    { Id: 342, Name: "Pishin" },
    { Id: 343, Name: "Qalandarabad" },
    { Id: 344, Name: "Qamber Ali Khan" },
    { Id: 345, Name: "Qasba gujrat" },
    { Id: 346, Name: "Qazi ahmed" },
    { Id: 347, Name: "Qila Deedar Singh" },
    { Id: 348, Name: "Quaid Abad" },
    { Id: 349, Name: "Quetta" },
    { Id: 350, Name: "Rahim Yar Khan" },
    { Id: 351, Name: "Rahwali" },
    { Id: 352, Name: "Raiwind" },
    { Id: 353, Name: "Rajana" },
    { Id: 354, Name: "Rajanpur" },
    { Id: 355, Name: "Rangoo" },
    { Id: 356, Name: "Ranipur" },
    { Id: 357, Name: "Rato Dero" },
    { Id: 358, Name: "Rawalakot" },
    { Id: 359, Name: "Rawat" },
    { Id: 360, Name: "Renala khurd" },
    { Id: 361, Name: "Risalpur" },
    { Id: 362, Name: "Rohri" },
    { Id: 363, Name: "Sadiqabad" },
    { Id: 364, Name: "Sagri" },
    { Id: 365, Name: "Sahiwal" },
    { Id: 366, Name: "Saidu sharif" },
    { Id: 367, Name: "Sajawal" },
    { Id: 368, Name: "Sakhi Sarwar" },
    { Id: 369, Name: "Samanabad" },
    { Id: 370, Name: "Sambrial" },
    { Id: 371, Name: "Samma satta" },
    { Id: 372, Name: "Sanghar" },
    { Id: 373, Name: "Sanghi" },
    { Id: 374, Name: "Sangla Hills" },
    { Id: 375, Name: "Sangote" },
    { Id: 376, Name: "Sanjarpur" },
    { Id: 377, Name: "Sanjwal" },
    { Id: 378, Name: "Sara e naurang" },
    { Id: 379, Name: "Sara-E-Alamgir" },
    { Id: 380, Name: "Sarai alamgir" },
    { Id: 381, Name: "Sargodha" },
    { Id: 382, Name: "Satiana" },
    { Id: 383, Name: "Sehar baqlas" },
    { Id: 384, Name: "Sehwan Sharif" },
    { Id: 385, Name: "Sekhat" },
    { Id: 386, Name: "Shadiwal" },
    { Id: 387, Name: "Shah kot" },
    { Id: 388, Name: "Shahdad kot" },
    { Id: 389, Name: "Shahdadpur" },
    { Id: 390, Name: "Shahdara" },
    { Id: 391, Name: "Shahpur chakar" },
    { Id: 392, Name: "Shahpur Saddar" },
    { Id: 393, Name: "Shakargarh" },
    { Id: 394, Name: "Shamsabad" },
    { Id: 395, Name: "Shankiari" },
    { Id: 396, Name: "Shedani sharif" },
    { Id: 397, Name: "Sheikhupura" },
    { Id: 398, Name: "Sheikhupura" },
    { Id: 399, Name: "Shemier" },
    { Id: 400, Name: "Shikar pur" },
    { Id: 401, Name: "Shorkot" },
    { Id: 402, Name: "Shorkot Cantt" },
    { Id: 403, Name: "Shuja Abad" },
    { Id: 404, Name: "Sialkot" },
    { Id: 405, Name: "Sibi" },
    { Id: 406, Name: "Sihala" },
    { Id: 407, Name: "Sikandarabad" },
    { Id: 408, Name: "Sillanwali" },
    { Id: 409, Name: "Sita road" },
    { Id: 410, Name: "Skardu" },
    { Id: 411, Name: "Skrand" },
    { Id: 412, Name: "Sohawa" },
    { Id: 413, Name: "Sohawa district daska" },
    { Id: 414, Name: "Sukkur" },
    { Id: 415, Name: "Sumandari" },
    { Id: 416, Name: "Swabi" },
    { Id: 417, Name: "Swat" },
    { Id: 418, Name: "Swatmingora" },
    { Id: 419, Name: "Takhtbai" },
    { Id: 420, Name: "Talagang" },
    { Id: 421, Name: "Talamba" },
    { Id: 422, Name: "Talhur" },
    { Id: 423, Name: "Tandiliyawala" },
    { Id: 424, Name: "Tando adam" },
    { Id: 425, Name: "Tando Allah Yar" },
    { Id: 426, Name: "Tando jam" },
    { Id: 427, Name: "Tando Muhammad Khan" },
    { Id: 428, Name: "Tank" },
    { Id: 429, Name: "Tarbela" },
    { Id: 430, Name: "Tarmatan" },
    { Id: 431, Name: "Tatlay Wali" },
    { Id: 432, Name: "Taunsa sharif" },
    { Id: 433, Name: "Taxila" },
    { Id: 434, Name: "Tharo shah" },
    { Id: 435, Name: "Thatta" },
    { Id: 436, Name: "Theing jattan more" },
    { Id: 437, Name: "Thull" },
    { Id: 438, Name: "Tibba sultanpur" },
    { Id: 439, Name: "Toba Tek Singh" },
    { Id: 440, Name: "Topi" },
    { Id: 441, Name: "Toru" },
    { Id: 442, Name: "Tranda Muhammad Pannah" },
    { Id: 443, Name: "Turbat" },
    { Id: 444, Name: "Ubaro" },
    { Id: 445, Name: "Ubauro" },
    { Id: 446, Name: "Ugoke" },
    { Id: 447, Name: "Ukba" },
    { Id: 448, Name: "Umer Kot" },
    { Id: 449, Name: "Upper deval" },
    { Id: 450, Name: "Usta Muhammad" },
    { Id: 451, Name: "Vehari" },
    { Id: 452, Name: "Village Sunder" },
    { Id: 453, Name: "Wah cantt" },
    { Id: 454, Name: "Wahi hassain" },
    { Id: 455, Name: "Wahn Bachran" },
    { Id: 456, Name: "Wan radha ram" },
    { Id: 457, Name: "Warah" },
    { Id: 458, Name: "Warburton" },
    { Id: 459, Name: "Wazirabad" },
    { Id: 460, Name: "Yazman mandi" },
    { Id: 461, Name: "Zafarwal" },
    { Id: 462, Name: "Zahir Peer" }
  ]
}
